# -*- coding: utf-8 -*-
"""python-demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UH8T-p8XlaaZ6GfA71wdbOk6hopGigJ9
"""

class MyClass:
  def __init__(self, num):
    self._num = num       # Protected
  def display(self):
    print(f"The Number is: {self._num}")
class Child(MyClass):
  def show_parent(self):
    print(f"Access the Number from child class: {self._num}")

m = MyClass(100)

m.display()

ch = Child(99)

ch.show_parent()

ch.display()